/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ActivityLogSchema extends BaseModel {
  static $columns = ['id', 'userId', 'action', 'target', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = ActivityLogSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
  @column()
  declare action: string
  @column()
  declare target: string
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class BlogTagSchema extends BaseModel {
  static $columns = ['blogId', 'tagId', 'createdAt', 'updatedAt'] as const
  $columns = BlogTagSchema.$columns
  @column()
  declare blogId: string
  @column()
  declare tagId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlogVersionTagSchema extends BaseModel {
  static $columns = ['blogVersionId', 'tagId', 'createdAt', 'updatedAt'] as const
  $columns = BlogVersionTagSchema.$columns
  @column()
  declare blogVersionId: string
  @column()
  declare tagId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlogVersionSchema extends BaseModel {
  static $columns = ['id', 'blogId', 'version', 'changeType', 'slugId', 'title', 'thumbnailId', 'description', 'content', 'changedFields', 'createdAt', 'updatedAt', 'isActive', 'isPinned', 'authorId', 'editorId'] as const
  $columns = BlogVersionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare blogId: string
  @column()
  declare version: number
  @column()
  declare changeType: string
  @column()
  declare slugId: string
  @column()
  declare title: string
  @column()
  declare thumbnailId: string | null
  @column()
  declare description: string | null
  @column()
  declare content: any
  @column()
  declare changedFields: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare isActive: boolean
  @column()
  declare isPinned: boolean
  @column()
  declare authorId: string | null
  @column()
  declare editorId: string | null
}

export class BlogSchema extends BaseModel {
  static $columns = ['id', 'slugId', 'title', 'thumbnailId', 'description', 'content', 'tags', 'createdAt', 'updatedAt', 'isActive', 'isPinned', 'authorId', 'editorId'] as const
  $columns = BlogSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare slugId: string
  @column()
  declare title: string
  @column()
  declare thumbnailId: string | null
  @column()
  declare description: string | null
  @column()
  declare content: any
  @column()
  declare tags: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare isActive: boolean
  @column()
  declare isPinned: boolean
  @column()
  declare authorId: string | null
  @column()
  declare editorId: string | null
}

export class BlogsProjectSchema extends BaseModel {
  static $columns = ['projectId', 'blogId', 'createdAt', 'updatedAt'] as const
  $columns = BlogsProjectSchema.$columns
  @column()
  declare projectId: string
  @column()
  declare blogId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MediaTagSchema extends BaseModel {
  static $columns = ['mediaId', 'tagId', 'createdAt', 'updatedAt'] as const
  $columns = MediaTagSchema.$columns
  @column()
  declare mediaId: string
  @column()
  declare tagId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MediaSchema extends BaseModel {
  static $columns = ['id', 'driveKey', 'mimeType', 'name', 'extension', 'size', 'hash', 'tags', 'createdAt', 'updatedAt'] as const
  $columns = MediaSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare driveKey: string
  @column()
  declare mimeType: string
  @column()
  declare name: string
  @column()
  declare extension: string
  @column()
  declare size: number
  @column()
  declare hash: string
  @column()
  declare tags: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['id', 'name', 'isProtected', 'createdAt', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare isProtected: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['id', 'isActive', 'isPinned', 'title', 'thumbnailId', 'description', 'tags', 'createdAt', 'updatedAt', 'links'] as const
  $columns = ProjectSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare isPinned: boolean | null
  @column()
  declare title: string
  @column()
  declare thumbnailId: string | null
  @column()
  declare description: string | null
  @column()
  declare tags: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare links: any | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['key', 'points', 'expire'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare key: string
  @column()
  declare points: number
  @column()
  declare expire: bigint | number | null
}

export class RoleMediaTagSchema extends BaseModel {
  static $columns = ['roleId', 'tagId', 'createdAt', 'updatedAt'] as const
  $columns = RoleMediaTagSchema.$columns
  @column()
  declare roleId: number
  @column()
  declare tagId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['roleId', 'permissionId', 'createdAt', 'updatedAt'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare roleId: number
  @column()
  declare permissionId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'name', 'isProtected', 'createdAt', 'updatedAt', 'canAccessAllMediaTags'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare isProtected: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare canAccessAllMediaTags: boolean
}

export class TagSchema extends BaseModel {
  static $columns = ['id', 'name', 'type', 'createdAt', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TokenSchema extends BaseModel {
  static $columns = ['id', 'userId', 'type', 'token', 'expiresAt', 'createdAt', 'updatedAt'] as const
  $columns = TokenSchema.$columns
  @column({ isPrimary: true })
  declare id: string | null
  @column()
  declare userId: string | null
  @column()
  declare type: string
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserProfileSchema extends BaseModel {
  static $columns = ['id', 'userId', 'avatarId', 'bio', 'createdAt', 'updatedAt'] as const
  $columns = UserProfileSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
  @column()
  declare avatarId: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['userId', 'roleId', 'createdAt', 'updatedAt'] as const
  $columns = UserRoleSchema.$columns
  @column()
  declare userId: string
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'username', 'email', 'password', 'isEmailVerified', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare fullName: string
  @column()
  declare username: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare isEmailVerified: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
